@version: 3.38
@module mod-http

options {
    keep-hostname(yes);
    stats(freq(0));
    use-dns(no);
};

source s_agent_tcp {
    network(
        port(601)
        transport("tcp")
    );
};

source s_external_udp {
    network(
        port(514)
        transport("udp")
    );
};

destination d_elasticsearch {
    http(
        url("http://elasticsearch:9200/_bulk")
        method("POST")
        headers("Content-Type: application/x-ndjson")
        body("$(format-json --scope none --omit-empty-values index._index=syslog-${S_YEAR}.${S_MONTH})\n$(format-json --scope none --omit-empty-values --pair @timestamp=$ISODATE --pair host.name=$HOST --pair host.ip=$SOURCEIP --pair message=$MESSAGE --pair process.name=$PROGRAM --pair event.kind=event --pair event.type=log --pair event.dataset=syslog.forwarded --pair ecs.version=8.0.0)")
        body-suffix("\n")
        batch-lines(32)
        timeout(10)
    );
};

log {
    source(s_agent_tcp);
    destination(d_elasticsearch);
};

log {
    source(s_external_udp);
    destination(d_elasticsearch);
};