services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
    logging:
      driver: journald
      options:
        labels: "application"
        tag: "elasticsearch|{{.ImageName}}|{{.DaemonName}}"

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.2
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
    ports:
      - "5601:5601"
    logging:
      driver: journald
      options:
        labels: "application"
        tag: "kibana|{{.ImageName}}|{{.DaemonName}}"

volumes:
  esdata:
    driver: local
