@version: 3.38

options {
    keep-hostname(yes);
    stats_freq(0);
    use-dns(no);
};

source s_kibana {
    file(
        "/logs/kibana.log"
        follow-freq(1)
        flags(no-parse)
    );
};

destination d_central_syslog {
    network(
        "syslog-ng"
        port(601)
        transport("tcp")
    );
};

log {
    source(s_kibana);
    destination(d_central_syslog);
};