@version: 3.38

options {
    keep-hostname(yes);
    stats_freq(0);
    use-dns(no);
};

source s_sshd {
    file(
        "/logs/auth.log"
        follow-freq(1)
        flags(no-parse)
        program-override("sshd")
    );
};

destination d_central_syslog {
    network(
        "syslog-ng"
        port(601)
        transport("tcp")
    );
};

log {
    source(s_sshd);
    destination(d_central_syslog);
};