@version: 3.38

options {
    keep-hostname(yes);
    stats(freq(0));
    use-dns(no);
};

source s_elasticsearch {
    file(
        "/logs/elasticsearch.log"
        follow-freq(1)
        flags(no-parse)
    );
};

destination d_central_syslog {
    network(
        "syslog-ng"
        port(601)
        transport("tcp")
    );
};

log {
    source(s_elasticsearch);
    destination(d_central_syslog);
};