@define elastic_host "localhost:9200"
@define elastic_user ""
@define elastic_pass ""

filter f_container {"${.journald.SYSLOG_IDENTIFIER}" eq "conmon"};

parser p_container_metadata {
    csv-parser(
        columns(PROGRAM, imagenameandtag,container.runtime)
        delimiters(chars("|"))
        template("${.journald.CONTAINER_TAG}")
    );
    csv-parser(
        columns(image.name, image.tag)
        delimiters(chars(":"))
        template("${imagenameandtag}")
    );
    map-value-pairs(
        pair("container.id", "${.journald.CONTAINER_ID}")
        pair("container.name", "${.journald.CONTAINER_NAME}")
        pair("container.image.tag", list("${image.tag}"))
        pair("container.image.name", "${image.name}")
        pair("event.action", "container.log")
        pair("event.kind", "event")
        pair("event.module", "container")
        pair("event.provider", "journald")
        pair("event.type", "log")
        pair("tags", list("syslog-ng"))
    );
};

template t_container {
    template("$(format_json --omit-empty-values --pair host.name=$HOST --pair host.ip=$SOURCEIP --pair @timestamp=$ISODATE --pair message=$MESSAGE --pair ecs.version=1.5.0 --key container.* --pair process.name=${PROGRAM} --key http.* --key user.* --key user_agent.* --key url.* --key source.* --key event.* tags=list($tags))\n");
};

destination d_container_file {
    file(
        "/var/log/container/$S_YEAR.$S_MONTH.$S_DAY/${.journald.CONTAINER_NAME}.log"
        create_dirs(yes)
    );
};

destination d_container_json {
    file(
        "/var/log/container/json/$S_YEAR.$S_MONTH.$S_DAY/${.journald.CONTAINER_NAME}.json"
        create_dirs(yes)
        template(t_container)
    );
};

destination d_container_elasticsearch {
    elasticsearch-http(
        url("http://`elastic_host`")
        index("container-${S_YEAR}.${S_MONTH}")
        headers("Content-Type: application/x-ndjson")
        custom-id("")
        type("")
        workers(4)
        batch-lines(16)
        timeout(10)
        template("$(template t_container)")
        disk-buffer(
            mem-buf-length(10000)
            disk-buf-size(10M)
            reliable(no)
        )
        persist-name("container")
        log-fifo-size(20000)
        user("${elastic_user}")
        password("${elastic_pass}")
    );
};

destination d_container {
    channel {
        parser(p_container_metadata);
        destination(d_container_json);
        destination(d_container_elasticsearch);
    };
};