filter f_remove_already_processed {
    not (program('conmon'))
};


log {
    source(s_src);

    if (filter(f_container)) {
        destination(d_container);
        flags(final);
    };

    filter(f_remove_already_processed);
    
};