filter f_remove_already_processed {
    not (program('conmon'))
};

source src {
    journald();
}

log {
    source(src);

    if (filter(f_container)) {
        destination(d_container);
        flags(final);
    };

    filter(f_remove_already_processed);
    
};